theme: jekyll-theme-hacker
title: Joy in Chibi

docs_list_title: joyful_pages
docs:

- title: Home
  url: index.md

- title: About Me
  url: about

- title: Projects
  url: projects

- title: Interests
  url: interests
